name = "PFR"
defaultTargets = ["PFR"]

[leanOptions]
autoImplicit = false        # Prevent typos to be interpreted as new free variables
relaxedAutoImplicit = false
pp.unicode.fun = true       # Pretty-print lambdas as `fun a ↦ b`
pp.proofs.withType = false  # Elide the types of proofs in terms

[[require]]
name = "LeanAPAP"
git = "https://github.com/YaelDillies/LeanAPAP.git"

[[lean_lib]]
name = "PFR"
